version: '3.7'

services:
  master:
    image: redis
    ports:
      - "6379:6379"
  slave1:
    image: redis
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6380:6379"
  slave2:
    image: redis
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6381:6379"
  sentinel1:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000    
    restart: always
    ports:
      - 26379:26379
  sentinel2:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000    
    restart: always
    ports:
      - 26380:26379